Build erlang 25.3.2.7 and 26.1.2
(current latest for these major versions)

Compilation of 26.1.2 fails on bionic with the following error, so it
is skipped for now

```
nifs/common/prim_tty_nif.c:46:10: fatal error: termcap.h: No such file
or directory
```