Build erlang 26.0 (#3)
Compilation fails on bionic with the following error, so it is skipped
for now

```
nifs/common/prim_tty_nif.c:46:12: fatal error: curses.h: No such file or directory
```